### ISSUE TITLE
Default display size too small

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/Pi_grammer#2]
When I start up the pi with a monitor plugged into the HDMI, then it seems to auto-choose a good resolution.

If I start up without a display plugged in, then it sets the resolution way too low and it's a pain to navigate files for further troubleshooting.

It'd be rad if it could always start up at a good resolution for our larger monitors.

**Comment by ToniCorinne** [comment]
@lewispg228 is this still a thing, or can we close this issue out?

**Comment by lewispg228** [comment]
@ToniCorinne Thanks for pinging this. I've let it sit too long. This isn't really an issue anymore. We plug into various sized screens when booting up production units, so it's nice to have it auto-size to whatevers plugged in. Closing. Thanks!
